### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by muuvmuuv** [alessioalex/get-folder-size#18]
Since v2 you are only exporting ESM, we are using Node 14 but not ESM yet because it comes with other issues. Can you use something like esbuild to produce CommonJS and ESM builds?

**Comment by atjn** [comment]
I really don't want to double the size and complexity of the package if I can avoid it, so here's a few suggestions first, let me know if you can use any of them:

### 1) Use import
You can import ESM modules from CommonJS this way:
```js
const getFolderSize = (await import("get-folder-size")).default;
```
Notice that it requires using the `await` keyword, so you can only use it inside an async function.

### 2) Stay on v2
There is nothing wrong with staying on version 2 for now. It has not been updated for almost three years because it just works. If you want to use it with promises, you can import it like this:
```js
const util = require("util");
const getFolderSize = util.promisify(require("get-folder-size"));
```

**Comment by muuvmuuv** [comment]
I will try the first Approach later. But will it really increase the size? Since tree shaking it should not. Only the project itself my propably double in size not the lib hence it wont import both.

**Comment by muuvmuuv** [comment]
```
const getFolderSize = (await import("get-folder-size")).default;
```

works just fine. I will use that since it's only for a project's script tool.

**Comment by atjn** [comment]
Great! In theory, you are right, tree shaking should remove all unused code, but in practice I don't see any way to properly tree shake this setup, and many projects don't even have a compile step, making it hard to do any tree shaking at all.

I will update the readme with these examples and wait to see if it becomes a large enough issue to justify the extra bulk :)

**Comment by acidjazz** [comment]
@muuvmuuv this does not work for my [oclif](https://oclif.io/) tool and has forced me to go back to v2 - i would suggest maybe doubling the complexity/size so more poeple can use this version?

**Comment by atjn** [comment]
@acidjazz as far as I can tell, v3 should work just fine with oclif. If you want me to look more into it, please open a new issue and include steps to reproduce your issue.

**Comment by acidjazz** [comment]
Well my issue is this exact error - even with trying 
```ts
const getFolderSize = (await import("get-folder-size")).default;
```

i've resulted to using v2

**Comment by atjn** [comment]
@acidjazz it should not be possible to receive the `ERR_REQUIRE_ESM` error code when using the `await import()` method. It also shouldn't be necessary to use that method, since oclif works just fine with the standard `import .. from` method.

There are a million different things you could have done to get this error message. If you're not willing to create a new issue with steps I can use to reproduce your issue, there's no way I can help you.
