### ISSUE TITLE
Support Node.js 12?

### ISSUE THREAD

**Issue by ryanblock** [alessioalex/get-folder-size#20]
I see that as of earlier this year, the minimum version of Node.js specified in package.json.engines is 14, and that you're using some that shiny new syntax [like optional chaining](https://github.com/alessioalex/get-folder-size/blob/master/index.js#L57).

However, we use this project in a Node 12 app; [Node 12 is the active LTS](https://nodejs.org/en/about/releases/) until later this year, then maintenance LTS through 2023. A lot of folks can be counted on to use 12 for quite some time (ourselves included over at github.com/architect).

Any chance I can convince you to avoid using the Node 14-specific syntax so 3.x can continue to be used with Node 12 projects and systems?

Happy to PR if welcomed. Thanks!

**Comment by atjn** [comment]
Hello :)

> Node 12 is the active LTS until later this year, then maintenance LTS through 2023

You are describing Node 14, which we do support. Node 12 is already Maintenance LTS and will stop receiving security updates in less than a year.

The idea with version 3 of this package, was to "rip off the bandaid" and completely shed any legacy code, which also means [limiting support for CommonJS modules](https://github.com/alessioalex/get-folder-size#how-do-i-import-it-from-a-commonjs-module) (I'm not sure what you use in your project). We didn't see this as a big problem, since people are welcome to stay on version 2, which hasn't needed an update in years because it just works as intended.

If you're willing to submit a PR for this, then I'll be glad to accept it, but I will be removing the changes again when Node 12 goes EOL :)

**Comment by ryanblock** [comment]
Yeah, fair, off by one row error. Serves me right for opening an issue fairly exhausted at the end of the day. :)

I'd say your point is totally reasonable, and with 12 EOL in April 22, prob not worth it at this point!
