### ISSUE TITLE
Returned size includes the size of an empty folder for each ignored top-level directory

### ISSUE THREAD

**Issue by Slapbox** [alessioalex/get-folder-size#26]
eg, we exclude one path, but the size returned is 4096 larger than expected, because it counts the size of the ignored folder as if it were an empty folder, rather than non-existent.

I'm not sure if this is a bug or a design choice.

Thanks for the great work!

**Comment by atjn** [comment]
The folder size should be ignored. Maybe your ignore pattern requires a slash at the end of the path? In that case, the folder itself is not ignored because its path ends in the name of the folder, without any slash.

I can't really help you more than that unless you post some code that I can run to see the issue myself :)

**Comment by Slapbox** [comment]
Thanks for your reply @atjn!

This is the code:

```js
const { size: requiredSpace } = await getFolderSize(getRootFolder(), {
      ignore: /backup/,
})
```

And it was run on Kubuntu 22.10 to produce the noted issue.

**Comment by atjn** [comment]
When I run the following code:

![Screenshot from 2023-03-12 00-35-07](https://user-images.githubusercontent.com/20535393/224516378-2154c333-2fa1-430e-9ca4-c723c36ebbea.png)

..the result is `4096`, which is correct because that is the size of the `test` folder, which is not ignored. Then if I change the ignore pattern to `/test/`, the result is `0` which is also expected because both folders are now matched by the ignore pattern. Are you seeing different results than this?

**Comment by Slapbox** [comment]
I just re-tested and it appears that I was mistaken - or at least that this cannot be reproduced with the code I provided (which is the code we settled on.)

So I'm probably mistaken. Apologies for the extra work.
